### ISSUE TITLE
failed to build on windows when python is intalled in custom folders

### ISSUE THREAD

**Issue by hxhc** [takanori-fujiwara/ccpca#3]
hi, I found it failed to intall ccpca on windows because at [this line](https://github.com/takanori-fujiwara/ccpca/blob/67a775c3481e37d5cefd4764f1dc6d9604ac05b3/ccpca/setup.py#L98C13-L98C13) python version is determined by folder name. However, if the folder name for python39 is py39, then `pyver` is py39, instead of python39, and thus the `pythonlib_path` will be py3.lib instead of python39.lib. As a result, when linking to pythonlib, it fails.

I recommend replace this line with `pyver = f"python{sys.version_info.major}{sys.version_info.minor}"`, which solves the issue. Since it is a minor issue, I don't post a pr. Hope you can fix it soon. 

Anyway, ccpca is a very good lib for EDA. I loves it and thanks a lot for your work.

**Comment by takanori-fujiwara** [comment]
I merged your request. Thank you!

**Comment by takanori-fujiwara** [comment]
Solved.
